function y = myfun(t,x)

for k = 1:length(t)
     q = x(k,1:2)';
end

[qd,dqd,ddqd] = desired_trajectory(t);

q_bar = q - qd;
A = diag([100 90]);
z = A*q_bar;
psi_z  = psi_sat(z);
dq_r  = dqd - psi_z;

% Regresor

q1 = q(1);
q2 = q(2);

U = [cos(q2)*(2*ddqd(1)+ddqd(2)) - dq_r(2)*(dq_r(1)+dq_r(2))*sin(q2) - dq_r(2)*dq_r(1)*sin(q2), ...
     0, ...
     ddqd(1), ...
     ddqd(2), ...
     0, ...
     dq_r(1), ...
     0, ...
     sin(q1), ...
     sin(q1+q2), ...
     0;

     0, ...
     ddqd(1)*cos(q2) + dq_r(1)*dq_r(1)*sin(q2), ...
     0, ...
     0, ...
     ddqd(1)+ddqd(2), ...
     0, ...
     dq_r(2), ...
     0, ...
     0, ...
     sin(q1+q2)];
 
I = U' * U;

 y = I;

