function U = regressor_U(q, dq_r, ddqd)

q1 = q(1);
q2 = q(2);
dq_r1 = dq_r(1);
dq_r2 = dq_r(2);
ddqd1 = ddqd(1);
ddqd2 = ddqd(2);

U = [cos(q2)*(2*ddqd1+ddqd2) - dq_r2*(dq_r1+dq_r2)*sin(q2) - dq_r2*dq_r1*sin(q2), ...
     0, ...
     ddqd1, ...
     ddqd2, ...
     0, ...
     dq_r1, ...
     0, ...
     sin(q1), ...
     sin(q1+q2), ...
     0;

     0, ...
     ddqd1*cos(q2) + dq_r1*dq_r1*sin(q2), ...
     0, ...
     0, ...
     ddqd1+ddqd2, ...
     0, ...
     dq_r2, ...
     0, ...
     0, ...
     sin(q1+q2)];

% Regresor desacotado (depende de \ddot q_r)

% U = [cos(q2)*(2*ddq_r(1)+ddq_r(2)) - dq_r(2)*(dq1+dq2)*sin(q2) - dq2*dq_r(1)*sin(q2), ...
%      0, ...
%      ddq_r(1), ...
%      ddq_r(2), ...
%      0, ...
%      dq_r(1), ...
%      0, ...
%      sin(q1), ...
%      sin(q1+q2)...
%      0;
% 
%      0, ...
%      ddq_r(1)*cos(q2) + dq1*dq_r(1)*sin(q2), ...
%      0, ...
%      0, ...
%      ddq_r(1)+ddq_r(2), ...
%      0, ...
%      dq_r(2), ...
%      0, ...
%      0, ...
%      sin(q1+q2)];

end